# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 11) do

  create_table "confirmations", :force => true do |t|
    t.column "related_url", :string
    t.column "user_id",     :integer,  :limit => 10
    t.column "number",      :string
    t.column "created_at",  :datetime
  end

  create_table "posts", :force => true do |t|
    t.column "r32_id",     :string
    t.column "title",      :string
    t.column "content",    :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "posts", ["r32_id"], :name => "index_posts_on_r32_id"

  create_table "r32s", :force => true do |t|
    t.column "user_id",               :integer, :limit => 10
    t.column "chassis",               :string,  :limit => 5
    t.column "edition_number",        :integer, :limit => 4
    t.column "year",                  :integer, :limit => 4
    t.column "interior",              :string,  :limit => 50
    t.column "color",                 :string,  :limit => 50
    t.column "vin",                   :string
    t.column "purchased_on",          :date
    t.column "preordered",            :boolean,               :default => false
    t.column "for_sale",              :boolean,               :default => false
    t.column "notes",                 :string
    t.column "mods",                  :string
    t.column "created_at",            :date
    t.column "updated_at",            :date
    t.column "picture_url",           :string
    t.column "picture_upload",        :string
    t.column "uploaded_picture_name", :string
    t.column "totaled",               :boolean,               :default => false
    t.column "mileage",               :integer, :limit => 10
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "users", :force => true do |t|
    t.column "first_name", :string,  :limit => 50
    t.column "last_name",  :string,  :limit => 50
    t.column "email",      :string
    t.column "password",   :string
    t.column "city",       :string
    t.column "state",      :string,  :limit => 2
    t.column "vortex_id",  :string
    t.column "website",    :string
    t.column "created_at", :date
    t.column "updated_at", :date
    t.column "hide_email", :boolean
    t.column "latitude",   :string
    t.column "longitude",  :string
  end

end
